#! /bin/sh -e

overwrite="$1"

mydir=`dirname "$0"`
params=$($mydir/get_params.py $mydir/../okboard.cf)

# update C++ code
head_decl=$mydir/../curve/curve_match.h
head_def=$mydir/../curve/default_params.h

cat $head_decl | sed -n  '/BEGIN PARAMS/,/END PARAMS/ p' | grep -v '/\*' | tr -d ';' | (
    echo "/* file generated by "`basename "$0"`" */"
    echo "static Params default_params = {"
    while read type name ; do
	value=`echo "$params" | grep "^$name " | awk '{ print $2 }'`
	[ -n "$value" ] || value=0
	echo "  $value, // $name"
    done
    echo "};"
) > "$head_def.tmp"

if cmp "$head_def.tmp" "$head_def" >/dev/null ; then
    rm -f "$head_def.tmp"
else
    echo "=== change to file "`realpath "$head_def"`" ==="
    diff -u "$head_def" "$head_def.tmp" || true
    if [ -n "$overwrite" ] ; then
	mv -fv "$head_def.tmp" "$head_def"
	echo "File updated"
    else
	echo "*** Add a nonempty parameter to update file !"
	exit 1
    fi
fi
     
echo "OK"
